name: Crawl JavBus Actresses

on:
  workflow_dispatch:
    inputs:
      censored_end_page:
        description: 'Censored End Page (e.g., 1019)'
        required: true
        default: '1019'
      uncensored_end_page:
        description: 'Uncensored End Page (e.g., 443)'
        required: true
        default: '443'
      start_page:
        description: 'Start Page (e.g., 1)'
        required: true
        default: '1'

permissions:
  contents: write  # 授予写权限以提交文件

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install curl_cffi beautifulsoup4

      - name: Configure Git
        run: |
          git config --global user.name "hhsw2015"
          git config --global user.email "hhsw2015@gmail.com"

      - name: Run crawler
        env:
          CENSORED_END_PAGE: ${{ github.event.inputs.censored_end_page }}
          UNCENSORED_END_PAGE: ${{ github.event.inputs.uncensored_end_page }}
          START_PAGE: ${{ github.event.inputs.start_page }}
        run: |
          python crawl.py

      - name: Commit and push changes
        if: always()  # 无论爬虫成功与否都尝试提交
        run: |
          git add censored.txt uncensored.txt
          git commit -m "Final commit after crawl" || echo "No changes to commit"
          git push || echo "Push failed, possibly no changes or permission issue"
